apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ required "missing deployment name" .Values.zipkin.deployment.name}} 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: zipkin-api 
  template: 
    metadata:
      labels: 
        app: zipkin-api
    spec:
      containers:
      - name: zipkin-api-service
        image: openzipkin/zipkin:{{ .Values.zipkin.imageVersion }}
        ports:
        - containerPort: {{ .Values.zipkin.queryPort }}
        env:
        - name: ES_INDEX
          value: {{required "A valid .Values.elastic.es_index entry required!" .Values.elastic.es_index }}
        - name: STORAGE_TYPE
          value: {{required "A valid .Values.elastic.storage_type entry required!" .Values.elastic.storage_type }}
        - name: ES_HOSTS
          value: {{required "A valid .Values.elastic.es_host entry required!" .Values.elastic.es_host }}
        - name: ES_DATE_SEPARATOR
          value: {{ .Values.elastic.es_date_separator }}
        - name: ES_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: zipkin-es-auth
              key: username
        - name: ES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: zipkin-es-auth
              key: password
        - name: ZIPKIN_UI_SEARCH_ENABLED
          value: {{ .Values.zipkin.opt.searchEnabled }}
        - name: QUERY_ENABLED
          value: {{ .Values.zipkin.opt.queryEnabled }}

---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ required "missing deployment name" .Values.zipkin_ui.deployment.name}} 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: zipkin-ui
  template: 
    metadata:
      labels: 
        app: zipkin-ui
    spec:
      containers:
      - name: zipkin-ui-service
        image: openzipkin/zipkin:{{ .Values.zipkin.imageVersion }}
        ports:
        - containerPort: {{ .Values.zipkin_ui.queryPort }}
        env:
        - name: ES_INDEX
          value: {{required "A valid .Values.elastic.es_index entry required!" .Values.elastic.es_index }}
        - name: STORAGE_TYPE
          value: {{required "A valid .Values.elastic.storage_type entry required!" .Values.elastic.storage_type }}
        - name: ES_HOSTS
          value: {{required "A valid .Values.elastic.es_host entry required!" .Values.elastic.es_host }}
        - name: ES_DATE_SEPARATOR
          value: {{ .Values.elastic.es_date_separator }}
        - name: ES_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: zipkin-es-auth
              key: username
        - name: ES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: zipkin-es-auth
              key: password
        - name: ZIPKIN_UI_ENVIRONMENT
          value: {{ required "environment param is required" .Values.zipkin_ui.ui_environment}}
        - name: ZIPKIN_UI_SEARCH_ENABLED
          value: "true"