---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: ingress
  chart:
    git: ssh://git@github.com:Krishna7ps/flux.git
    ref: master
    path: Chart
  values:
    image:
      repository: bitnami/nginx-ingress-controller
      tag: 0.43.0-debian-10-r15
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
    service:
      type: LoadBalancer

